### ISSUE TITLE
Saving of amendments to fundraisers

### ISSUE THREAD

**Issue by harrystroud** [NickBurneConsulting-GivePanel/givepanel#104]
**Is your feature request related to a problem? Please describe.**
I didn't know as a user when I clicked save if it had actually saved my edits. I think it would work best if we notify users that their save has worked.  e.g. a green tick or a ''your amendments have been saved''
![screenshot 2019-02-12 at 13 38 30](https://user-images.githubusercontent.com/45844654/52639294-d77c5800-2ecb-11e9-9ce4-890604051b95.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nickburne** [comment]
Solution:

Under Save button add text

Saving... 

Saved!

Small grey text no underline

**Comment by jonrandahl** [comment]
This is displaying "Saving ..." while saving but haven't gotten the final message displaying. 

Shelving further changes as this does what it needs to for the time being.

**Comment by nickburne** [comment]
Align to left of Save button
