### ISSUE TITLE
Transaction ID is not unique enough due to refunds and chargebacks

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#106]
Add 'Charge action type - e.g. C, S, R' to transaction ID

**Comment by jonrandahl** [comment]
This is now part of the new data structure and in place with the latest version of the uploader:

![image](https://user-images.githubusercontent.com/39102/52850532-a5593900-310b-11e9-8805-1e08ba605cde.png)


![image](https://user-images.githubusercontent.com/39102/52850544-abe7b080-310b-11e9-9612-6c00f433915d.png)
