### ISSUE TITLE
Make fields read only on donation card

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#122]
e.g. If there is an address for the transaction in the transaction report it should not be able to be editable by the user on the front end under the donations table / donations detail card

**Comment by jonrandahl** [comment]
Updated to reflect current display descisions

![image](https://user-images.githubusercontent.com/39102/53021767-d7430600-3451-11e9-8953-075dc1fa6480.png)

**Comment by jonrandahl** [comment]
Deployed to https://staging.givepanel.com for testing
