### ISSUE TITLE
Create Sands Charity Account for demo

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#125]

**Comment by nickburne** [comment]
PLus 3 more accounts:

GP test 1
GP test 2
GP test 3

**Comment by jonrandahl** [comment]
These are done, and I'd like some time for styling but it's not a priority

![image](https://user-images.githubusercontent.com/39102/53004065-4441a600-3428-11e9-84a5-8f7e33854b70.png)

**Comment by jonrandahl** [comment]
![image](https://user-images.githubusercontent.com/39102/53004159-85d25100-3428-11e9-8350-a9922406855c.png)
