### ISSUE TITLE
Labels do not update as expected on save

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#126]
When applying labels to fundraiser detail, the row details update correctly when adding new labels, however, they do not save in the right order when removing them.

This could be due to "Last in First Out" issues with Arrays?

**Comment by nickburne** [comment]
@jonrandahl - do a quick Loom video for @shramee ?

**Comment by jonrandahl** [comment]
@shramee my latest work can be found on this branch, please let me know if you have any questions!

https://github.com/NickBurneConsulting-GivePanel/givepanel/commit/e2d799b858cd0120c17975e6e5b30e021130d0ee

**Comment by givepanel** [comment]
Reopened to give @HelloTiago a chance to sort the page refresh issue.
