### ISSUE TITLE
Provision LIVE instance

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#132]

**Comment by jonrandahl** [comment]
Deployment has completed for both the hosting files and the cloud functions, you can see the "updated" site here:

https://givepanel-app.firebaseapp.com/

I have initiated our super-admin accounts and sent password reset requests to each of us. I have NOT used the weak password as in prior instances so you will need to reset before accessing the instance.

N.B. It seems we've already set up the sub-domain `app.givepanel.com` to point to the old firebase instance.

Could you please send the DNS Records for the sub-domain to me via slack so I can see what our next step is?

**Comment by jonrandahl** [comment]
Created ticket through the Trial account support system, received this response on submission:

> Thank you for contacting us. One of our support agents will respond to your question usually within 1 business day. Please note we can't guarantee a response time. In the meantime, please see our Free Trial FAQ or product documentation to see if your question may have already been answered there.
> Happy coding,
> Google Cloud Platform Support

**Comment by jonrandahl** [comment]
adding this link here for posterity::
https://support.google.com/cloud/contact/free_trial_support?authuser=1
