### ISSUE TITLE
Filter by Refunds and Chargebacks in Donation table

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#150]
Two separate filters

**Comment by jonrandahl** [comment]
This is implemented and I will push to staging next:

![image](https://user-images.githubusercontent.com/39102/53169227-91fb1180-35d4-11e9-93b3-de9f2fa27189.png)

**Comment by jonrandahl** [comment]
@nickburne updated on staging and tested, please advise.
