### ISSUE TITLE
Upload CSV progress can be overloaded by refreshing the whole page

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#155]
@shramee, 

When I just uploaded 3333 rows the dashboard was still updating. Nick logged in as super-admin and selected my test charity. When the dashboard loaded it had the totals as they were finished and there were no more updates; meanwhile, my dashboard was still updating? I refreshed the page and all the totals were then shown with no more progress needed...

Happy to chat about this and show you what I mean when we do speak!

**Comment by nickburne** [comment]
Test with a customer and it was the same. If they refresh the page all the data and totals display instantly...

**Comment by shramee** [comment]
This will be okay after optimizing queries to only include current month data (instead of loading everything there is to load) ;)
