### ISSUE TITLE
Changes to Sign up and Login

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#157]
1. Remove/archive Facebook Login
2. Sign up page has 4 fields - Charity name (Free text), Work email, Password, Confirm Password, Opt-in and link to login page.
3. Login page has 2 fields - email and password and link to sig up page
4. Fix uploader for new sign up by removing charity page ID

**Comment by jonrandahl** [comment]
This is now on staging for testing. Please note, we will need to create new accounts for testing but will still be able to switch via gp-admin.
