### ISSUE TITLE
Message Templates

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#17]
Under Account settings there should be a first tab that says "General"

Under General there should be a section to edit your "Message Template" and there should be an existing default message as follows:

"Hi [first name], thanks so much for doing a fundraiser for us! We'd love to know more about what motivated you to raise funds for us - you can chat with us here: [link]"

The template should pre-fill the first name and the link automatically.

The template needs to allow for the use of Emoji's.

**Comment by nickburne** [comment]
This should work similar to manage campaigns in Active Campaign

A simple list view of the templates with a "New Template" button top right. 

Each row would be a message title with an edit button on the far right.

**Comment by jonrandahl** [comment]
This is now on Staging, and Demo but the most recent is on Staging on #228

**Comment by nickburne** [comment]
Message button is missing on staging @jon-humphrey

**Comment by jonrandahl** [comment]
@nickburne, apologies but ...

1. which charity are you testing with, and 
2. have you created a message template first?

![image](https://user-images.githubusercontent.com/39102/54615307-c6d47a00-4a55-11e9-90d6-b5b070aef529.png)

**Comment by jonrandahl** [comment]
this is now on all public instances. closing
