### ISSUE TITLE
terms and conditions clause 9.5

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#176]
error reference source not found

**Comment by nickburne** [comment]
@jon-humphrey - have emailed solicitor to confirm this and copied you into the email

**Comment by nickburne** [comment]
@jon-humphrey - spoke to solicitor, we just need to completely remove clause 9.5

Thanks!

**Comment by jonrandahl** [comment]
@nickburne This is updated on each of the Staging, Demo, and Live instances;
@shramee & @HelloTiago when you pull down staging again this should merge in, please let me know if it doesn't!
