### ISSUE TITLE
On uploading of the same CSV twice, the totals on the dashboard double until refresh?

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#181]
On upload of a transaction report the dashboard widgets update their totals based on the transactions processed, which works exactly as expected:

![image](https://user-images.githubusercontent.com/39102/53653779-015fa980-3c44-11e9-9c02-98a09eb61756.png)

However, when you upload the same transaction report the dashboard widgets, total raised and average, double in number: 

![image](https://user-images.githubusercontent.com/39102/53653771-f9076e80-3c43-11e9-9a7d-911170a46b2d.png)

If you then reload the page the totals are as they were the initial upload?

![image](https://user-images.githubusercontent.com/39102/53653779-015fa980-3c44-11e9-9c02-98a09eb61756.png)

**Comment by jonrandahl** [comment]
@shramee I resolved this by using the Mapped Set to display the totals in the widgets which prevents duplicated entries from being displayed, can you think of any other way to do this?

**Comment by shramee** [comment]
Hi Jon,
I have removed that mapping code it doesn't happen anymore with the way we get data now 😄
