### ISSUE TITLE
removing firebase urls from live instance

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#188]
In order to have any emails coming from the live site not be associated with firebase we need to set some additional records for the givepanel.com domain:

Host | Type | Value
-- | -- | --
app.givepanel.com | TXT | v=spf1 include:_spf.firebasemail.com ~all
app.givepanel.com | TXT | firebase=givepanel-app
firebase1._domainkey.app.givepanel.com | CNAME | mail-app-givepanel-com.dkim1._domainkey.firebasemail.com.
firebase2._domainkey.app.givepanel.com | CNAME | mail-app-givepanel-com.dkim2._domainkey.firebasemail.com.

NB> It can take up to 48 hours to verify the domain changes. I will have to check firebase later to finish adding our custom domain.

**Comment by nickburne** [comment]
@jon-humphrey - this has been done. Assigning back to you to check and close once you are happy.

**Comment by jonrandahl** [comment]
I've just initiated the verification so I'll update again when this is done!

![image](https://user-images.githubusercontent.com/39102/54426976-142cb080-4711-11e9-814c-8cf3be6bd662.png)

**Comment by jonrandahl** [comment]
The verification has completed:

![image](https://user-images.githubusercontent.com/39102/54649954-2bb6c100-4aa4-11e9-9986-f4d6fe6d6e67.png)

Note the https://app.givepanel.com domain in the email address as well as the Action URL at the bottom; this holds true for all templates:
1. Email Verification (even if we're not using it)
2. Password Reset (need to add a ticket for this!)
3. Email address change (never used this, might come in handy later!)

Back over to you to close!
