### ISSUE TITLE
Don't listen to changes for transactions

### ISSUE THREAD

**Issue by shramee** [NickBurneConsulting-GivePanel/givepanel#196]
Just grab them once,
This will fix the issue where app gets quite a bit laggy as new CSV data is uploaded (tries to sync transactions with as they are uploaded).
Optionally, add a button to reload requests..? <- @nickburne @jonrandahl This is a maybe thing, let me know what you guys think :wink:

**Comment by nickburne** [comment]
@shramee - it is taking us a lot of time to understand your tickets and what you have ACTUALLY done. I don't want @jon-humphrey spending time trying to figure out what you have done from your code, when a simple comment on a ticket is much quicker.

Please update this ticket with what you have ACTUALLY done as we have tested on staging and there are still performance issues.

**Comment by shramee** [comment]
Hi @jonrandahl @nickburne,

Initially we were subscribed to changes, now we are grabbing data on demand.

We have a getTransactions method that grabs transactions when component is initially set up and when `Load data` button is clicked.

**Comment by nickburne** [comment]
@jon-humphrey - i don't know how to test for this so i will leave it to you to sign off. 

Data still seems very slow to me.
Assigning back to you.
