### ISSUE TITLE
Mobile and tablet notification

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#20]
For version 1 we will not be supporting mobile or tablet devices.

We need a simple screen notification when users visit the givepanel app on a mobile or tablet.

It should say something like 
Headline: "GivePanel only works on desktop right now"
Subline: "We want GivePanel to work seamlessly on smartphones and tablets. We're working on this but for now you have to use a laptop or desktop computer"

**Comment by jonrandahl** [comment]
This is in place now. 

![screenshot 2019-01-07 17 07 08](https://user-images.githubusercontent.com/39102/50782484-0b96a480-12a0-11e9-99cb-74f00e7e3a1c.png)
