### ISSUE TITLE
date of birth field to be separated into day/month and then year

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#214]
We need date of birth field to be separated into day/month and then year. This is because we will sometimes know the day/month but not know the year.

**Comment by jonrandahl** [comment]
@HelloTiago could you action this but read through these options first? 

1. We will need to split any already submitted birthday values by the day/month & year values;
2. We will need to then fill the new fields with these values or leave blank if empty;
3. We will then need to delete the current database birthday field as it won't be required any more.

Happy to discuss, let me know!

**Comment by jonrandahl** [comment]
@HelloTiago please create the three input fields on the front-end of the fundraiser details as discussed using simple select boxes for Date, Month, and Year and filled from a default calendar object. 

Add the simple validation to ensure no dates can be selected outside of the chosen month's length (29 for February, 30 for September, etc).

When saving to the DB, as the DB field type is a string we can just save the combined values as `MM-DD`, or if we get the year as well save them all as `YYYY-MM-DD`.

Then, to pre-select each input field on the front-end we can split the DB field value by the delimiter `-` and count the length of the zero-based result:

1 = MM & DD
2 = YYYY, MM, & DD

To be sure we always get at least MM-DD then please add a required validation if either the month or the date has been chosen.

Jon
