### ISSUE TITLE
marker in the GivePanel interface when a fundraiser has filled in their data

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#219]
Let's have a marker in the GivePanel interface when a fundraiser has filled in their data (Megan suggest a star)

**Comment by nickburne** [comment]
I want a green "person" icon if we the fundraiser has completed their data and a red "person" icon if they have not completed their data.

The icon should not appear at all until the Fundraiser's "new" label has gone.

The icon should appear in 2 places. 1) on the Fundraiser Table in the name column next to (after) their name) and 2) after/next to their name on the Fundaiser details card.

Icons should be:

https://fontawesome.com/icons/user-check?style=solid  in GREEN

https://fontawesome.com/icons/user-alt?style=solid in RED

**Comment by nickburne** [comment]
@jon-humphrey - assigned to you, you may want to assign to Tiago?

**Comment by jonrandahl** [comment]
@nickburne this is now in place as you can see here:
![image](https://user-images.githubusercontent.com/39102/55119345-6beff200-50e9-11e9-96e7-1c657217e485.png)
here:
![image](https://user-images.githubusercontent.com/39102/55119366-7e6a2b80-50e9-11e9-92c6-b0a298cf4ddf.png)
and here:
![image](https://user-images.githubusercontent.com/39102/55119381-90e46500-50e9-11e9-8eac-30e7dbaf9e1c.png)

However, I've had to use slightly different icons as the sets we have access to do not include the latest Font Awesome but rather: https://fontawesome.com/v4.7.0/

Will update onto staging with next push!

**Comment by jonrandahl** [comment]
On staging for review

**Comment by jonrandahl** [comment]
on staging for review @nickburne
