### ISSUE TITLE
Locking the data capture form

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#220]
We will lock form once it is completed and have message that says "This form has been completed. To contact our support please email [email] or call [phone]". PCUK will draft this message and we will make it editable in the form editor.

**Comment by jonrandahl** [comment]
Built and deployed to Staging

**Comment by jonrandahl** [comment]
Built and deployed to Demo

**Comment by jonrandahl** [comment]
Built and deployed to Live
