### ISSUE TITLE
Simply Form ID to single numbers 

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#230]
e.g. form id = 1
form id = 2

etc etc

**Comment by jonrandahl** [comment]
Are we actually doing this as we discussed that the ids are present on the settings > forms table and are now clickable?

![image](https://user-images.githubusercontent.com/39102/54483471-44786a00-484b-11e9-86c5-ba655b953ffb.png)


eg: YANtv4tKpxV4zxABDTes

**Comment by nickburne** [comment]
Yes, we still need to do this please.
