### ISSUE TITLE
Page Loading indicator 

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#236]
We'd like this to mimic GitHub's progress bar at the top of the browser window and be the GivePanel pink colour.

This would be below the admin toolbar though, I've made some changes to that and if you get latest from the Staging branch you will be up to date with everything.

**Comment by HelloTiago** [comment]
@jonrandahl Just open a PR for this (#240) with a small summary of what we discussed, explaining how it works. Over to you sir.
