### ISSUE TITLE
30 Day Default Date Range for all data

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#237]
We need to have a default limit of all returned data to be restricted to the last 30 days. This should speed up rendering times for all components as there will be a smaller data set to load.

This would solve #227, #195, and other loading speed related issues.

**Comment by shramee** [comment]
@jonrandahl This seems to be done too...

**Comment by nickburne** [comment]
@jon-humphrey to check code before closing. No need to check with Nick.

**Comment by jonrandahl** [comment]
this is now in place on all public instances
