### ISSUE TITLE
Global Date Range Selector

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#238]
• Applies to all sections of the site (e..g dashboard, fundraiser table,
donations table)
• Remembers date settings across all sections of the site until changed again
• Has pre-sets for common date ranges:
![image](https://user-images.githubusercontent.com/39102/54543254-38002880-4995-11e9-9241-04556a722dbc.png)

• Allows for custom dates to be selected
• Only shows exact transactions on those dates. E.g. only shows how much a fundraiser has actually raised between the dates selected
• Should default on the first usage to last 30 days
• App performance is needed, especially if the user decides to select the "All time" option

**Comment by shramee** [comment]
@jonrandahl I think you have taken care of this one...

Let me know if anything is required...
