### ISSUE TITLE
Change color of Data capture submit button to Facebook button colour

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#260]
e.g. the colour of the donate button on this page: 
https://www.facebook.com/donate/1668925226747570/

Facebook blue

**Comment by nickburne** [comment]
Pretty simple update @HelloTiago  but let me know if you have any questions :)

**Comment by HelloTiago** [comment]
@nickburne Easy enough! :D This is ready to be merged on #275

**Comment by jonrandahl** [comment]
this is actioned and live on the public instances.
