### ISSUE TITLE
Event selector for Fundraisers

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#269]
In the fundraiser details tab there should be an event drop down that allows users to select an event from a list of events for that fundraiser.

Only 1 event can be assigned to each Fundraiser. This event then needs to appear in the Export CSV file from fundraisers.

There will be an "Events" tab in Account Settings where users can add events.

There will be a default event added called "Birthday" and users can add more events.

The event "Birthday" should be automatically filled in if the title of the fundraiser includes "Birthday"

**Comment by jonrandahl** [comment]
- [ ] an "Events" tab in Account Settings where users can add events.
- [ ] a default event added called "Birthday" and users can add more events.
- [ ]  "Birthday" should be automatically filled in if the title of the fundraiser includes "Birthday"
- [ ] only 1 event can be assigned to each Fundraiser. 

https://www.useloom.com/share/2b70979e8c1c44fb81eab5dc68adcaa6

I forgot to show this is also in the CSV Export.

This is now on staging instance for approval.

**Comment by jonrandahl** [comment]
For to show this for updating charities:

https://www.useloom.com/share/6190fdbed2dc46d7b0d130d8f742b010
