### ISSUE TITLE
Limit data to nothing before 1/1/19

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#286]
The default for our sales process is the last 30 days. Because of 31 day months we should set this in the app as 32 days (to give 24 hours grace on the data)

But for some charities we will want to manually change the "account start date"

The limit itself could work 1 of 3 ways:

1. We could limit the data coming in to the database by not accepting date before the "account start date" using the cloud functions in the uploader.

OR 

2. We could parse the dates in the transaction report and if they include a date that is previous to the "account start date" it could reject the upload and give the user a warning.

OR

3. We could accept all data even if it's before the account start date and use the front end UI to limit the data visible (using the global date selector to limit the date range)

@jonrandahl - I would like feedback from the whole team on this and I will sign off the option before we do it.

**Comment by jonrandahl** [comment]
@shramee and @HelloTiago lets discuss this today?

**Comment by HelloTiago** [comment]
@jonrandahl @shramee Yap! What time works best for you guys?

**Comment by nickburne** [comment]
Ok, this ticket now is:

1. Date picker can't go back before 1/1/19

2. We parse the dates in the transaction report and if they include a date that is previous to 1/1/19  it rejects the upload and gives the user a warning.
