### ISSUE TITLE
Dashboard doesn't seem to load on initial log into site

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#288]
When we log into any of the instances we are now shown the "No data for these dates" message; 

![image](https://user-images.githubusercontent.com/39102/55156117-046d8d00-5151-11e9-8e6f-87261006670e.png)

when we navigate away and come back, or refresh the page, the data seems to come in:

![Screenshot 2019-03-28 12 00 36](https://user-images.githubusercontent.com/39102/55156177-249d4c00-5151-11e9-9ad2-b5e001ac1b4f.png)

**Comment by shramee** [comment]
@jonrandahl Not able to reproduce this on `staging` branch...

Is this happening on some other branch..?

**Comment by shramee** [comment]
Ohh sorry that's for admin dashboard...
Lemme test that :wink:

**Comment by jonrandahl** [comment]
@shramee - you can replicate this on any charity with data by clicking on the givepanel logo in the sidebar.

**Comment by jonrandahl** [comment]
@shramee I've just been flicking around my local instance and had this error thrown in the console:

```0.chunk.js:162873 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Fundraisers (created by FirestoreConnect(Fundraisers))
    in FirestoreConnect(Fundraisers) (created by Connect(FirestoreConnect(Fundraisers)))
    in Connect(FirestoreConnect(Fundraisers)) (created by Route)```

I've never seen this before on the site ... and wondered if you have?

**Comment by jonrandahl** [comment]
Right, I've just walked through the site again here on my local instance and there is still no error message so I think it must have been something else ... especially as we don't use the `componentWillUnMount`e event in our code.

I'll close this issue and do the live release as planned.
