### ISSUE TITLE
Filter for Optin Consent on Donations List and Details

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#29]
When someone donates on Facebook Giving tools they are given the option (via checkbox) to consent to email updates. When this happens the charities get an email address in their report.

We have had feedback that charities want to filter by this data point.

**Comment by nickburne** [comment]
@jon-humphrey - please make notes here of where you got to and assign to @shramee

**Comment by jonrandahl** [comment]
@shramee the issue as I can work out is that the filters for the bootstrap table are never checking for "empty" cells, it doesn't care about that. I have gone through the component documentation, as well as the issue tracker on the repo, and not been able to find anyone else asking for "filtering on empty cells". 

In the documentation, the filters work on a form field in the header - we've just hidden those fields and used the remote controls to trigger a filter.

I know we can filter an array (the type of data we're passing in via firestore) using the built in JS `Boolean` method like this example:

```
var arr = [0,1,2,"Thomas","false",false,true,null,3,4,undefined,5,"end"];
arr = arr.filter(Boolean);
// [1, 2, "Thomas", "false", true, 3, 4, 5, "end"]
```
https://stackoverflow.com/a/5443800/5760177

So I wondered if there was a way to trigger a filter like this example in the component documentation?

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Implement%20custom%20filter%20logic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

I'd love to hear your thoughts on this?
J

**Comment by HelloTiago** [comment]
Just finished implementing this and opened PR #266 - assigning to @jonrandahl for merging :)
