### ISSUE TITLE
Terms and Conditions clause 2.1

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#296]
Missing information and displaying `Error! Reference source not found.` in text.

Adjusted styling to mirror the rest of the layout, just waiting on feedback.

**Comment by nickburne** [comment]
Subject to: (a) the Customer’s application for a Subscription for a Trial Period being accepted; or, (b) the Customer purchasing the User Subscriptions in accordance with clause 9.1, the  restrictions set out in this clause 2 and the other terms and conditions of this agreement, GivePanel hereby grants to the Customer a non-exclusive, non-transferable right, without the right to grant sub-licences, to permit the Authorised Users to use the Services during the Subscription Term solely for the Customer's internal business operations.

**Comment by nickburne** [comment]
@jon-humphrey - see above for clause 2.1 - please update ASAP

**Comment by jonrandahl** [comment]
@nickburne 

![image](https://user-images.githubusercontent.com/39102/55243848-ed559a80-5237-11e9-873a-9668e0cfef1c.png)

Approve to go live please.

**Comment by jonrandahl** [comment]
On Live instance, will update other instances with later merges as this branch is now in the staging branch for all.
