### ISSUE TITLE
Opt-in for transaction upload

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#299]

**Comment by jonrandahl** [comment]
@nickburne I've done this this morning but would like your feedback before pushing anywhere:

https://www.useloom.com/share/b131f20a4b20457bbb9fc02829d4db34

**Comment by nickburne** [comment]
Awesome @jon-humphrey - 

Only thing is the copy should be 

"I agree that my transaction report has not been modified in any way since I requested it from Facebook"

Other than that I really like the UI. Good work! Proceed!

**Comment by jonrandahl** [comment]
integrated and on staging. Will update other instances on next deployment.
