### ISSUE TITLE
Wrong currency symbol for charities outside UK

### ISSUE THREAD

**Issue by harrystroud** [NickBurneConsulting-GivePanel/givepanel#302]
**Describe the bug**
Wrong currency symbol showing in the top fundraiser's table on the dashboard

**To Reproduce**
sign in as autism dogs charity
view dashboard 
note that the top fundraiser's values are set to pounds

**Expected behavior**
It should display the correct currency for the charity's country

**Comment by jonrandahl** [comment]
This is also present in the fundraiser details card.
