### ISSUE TITLE
HelpScout Issue - PCUK Data does not reflect the total shown on FB

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#307]
https://secure.helpscout.net/conversation/817098042/815?folderId=2830272

**Comment by harrystroud** [comment]
![image](https://user-images.githubusercontent.com/45844654/55466942-299e4780-55f8-11e9-957c-722be56196cd.png)

![image](https://user-images.githubusercontent.com/45844654/55466961-3327af80-55f8-11e9-9e07-f54a1f8f04d0.png)

**Comment by jonrandahl** [comment]
Closing this as we've worked out GP displays the amount raised including GiftAid while Facebook doesn't.
