### ISSUE TITLE
Birthday Filter throws error on save event

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#319]
if you select 'Filter Results' on the Fundraisers Tab, then select it to show 'No Birthday Fundraisers'... then subsequently click to edit one of these filtered results, when you click to add a label and it autosaves, it also auto refreshes the list of fundraisers back to the unfiltered results. So you essentially lose the one you were editing amongst the sea of results.

**Comment by jonrandahl** [comment]
This is currently actually throwing an error because the event dropdown field is not passing back any values if not chosen.

Investigating now.

**Comment by nickburne** [comment]
Not working for me on staging @jon-humphrey
