### ISSUE TITLE
Change start date filter to be between two dates on Fundraiser List

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#32]

**Comment by jonrandahl** [comment]
At this point this is unavailable for the React Table Component we're using:

https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/512

Please advise.

**Comment by nickburne** [comment]
@shramee - can you think of a way around this? Please don't do it, we just want to ask you the question...

**Comment by shramee** [comment]
This should be possible, we would probs need to edit the the component to add a new feature :wink:

**Comment by jonrandahl** [comment]
@shramee in the component's node_modules folder there's the filter for the dates, how difficult would it be to make our own Higher Order Component and pass in this functionality that way?

**Comment by shramee** [comment]
Ohh 😮

**Comment by shramee** [comment]
Need to look at the code before I can answer that reliably (with some time estimations) 😅

**Comment by nickburne** [comment]
@shramee - please provide estimations. We definitely need this!
