### ISSUE TITLE
$USD bug...

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#331]
<img width="490" alt="Screenshot 2019-04-11 at 14 12 50" src="https://user-images.githubusercontent.com/3784875/55965762-2138b300-5c6f-11e9-8d06-0f6a91c99382.png">
<img width="277" alt="Screenshot 2019-04-11 at 14 10 23" src="https://user-images.githubusercontent.com/3784875/55965764-21d14980-5c6f-11e9-8ea5-d1dc9c42f09d.png">

**Comment by nickburne** [comment]
Check out Roswelll Park account on live.

**Comment by jonrandahl** [comment]
okay!

**Comment by jonrandahl** [comment]
Need to push this to live instance in order to test solution.
