### ISSUE TITLE
Search for fundraisers and donations in fundraiser and donation lists

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#36]
This would be under features

**Comment by jonrandahl** [comment]
@shramee this is part of the bootstrap table component we've used and you can see how to do this in their examples:

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Table%20Search&selectedStory=Basic%20Search%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by jonrandahl** [comment]
@HelloTiago this should be similar to the birthday filter, albeit using a search field that is visible. Open to suggestions for the location and placement of the field and button group.

**Comment by HelloTiago** [comment]
@jonrandahl Whoops looks I opened the PR last Friday and forgot to mention it here! It's PR #224 and it's ready to be merged.
