### ISSUE TITLE
Upload process has no progress notification other than the actual upload

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#40]
ISSUE: When triggering a transaction report upload, while the upload progress shows in the modal dialogue, there is no further indication of processing or completion

SOLUTION: To incorporate a discreet progress ticker into the browser window top edge, much like [Best Practices in Designing Awesome Progress Bars](https://medium.com/@CanvasFlip/best-practices-in-designing-awesome-progress-bars-e051bef10c28)

ALTERNATIVES: Email the agent that the upload has completed; however, this seems to be counterintuitive as the data on the dashboard refreshes automatically.

**Comment by nickburne** [comment]
Please finish this one @shramee

**Comment by shramee** [comment]
Over to you for merging John ;)
