### ISSUE TITLE
Mobile notification page didn't appear when viewing site on in-app browser (Slack)

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#45]
So I click on a link to GivePanel in Slack on my iphone (the Slack iphone) app and it has it's own browser. 

The mobile notification page didn't appear.

I guess this may also happen from in-app browsers on Twitter and Facebook so worth fixing.

**Comment by jonrandahl** [comment]
@nickburne I have tested this with the new instances set up now and cannot reproduce? Could you verify this is still happening?

![image](https://user-images.githubusercontent.com/39102/51537263-f1cf9280-1e45-11e9-84f9-82e6f79626f5.png)
