### ISSUE TITLE
Work email is pre-filled from Facebook email on Sign up

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#48]
We don't want this as users will never see to put in their work email

![image](https://user-images.githubusercontent.com/3784875/50962911-30b72d00-14c3-11e9-82b9-ce4616345444.png)

**Comment by nickburne** [comment]
I would also like to strip out any non work email addresses at this point like "gmail" and "hotmail"

**Comment by jonrandahl** [comment]
The first point with having the field "pre-filled" has been resolved alongside Terms and Conditions #37 

![image](https://user-images.githubusercontent.com/39102/53092105-c35bda80-350b-11e9-8882-e32fb04272d7.png)

Further steps will be required for filtering the actual email addresses provided.
