### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#54]
<img width="510" alt="screenshot 2019-01-23 at 16 20 21" src="https://user-images.githubusercontent.com/3784875/51620718-e1ddae80-1f2a-11e9-890c-fd3005845544.png">

**Comment by jonrandahl** [comment]
Labels are now editable with the caveat that the colour choices need to be restricted to the bootstrap4 named colours otherwise the buttons do not show the corresponding colour for the label.

commit 7b4808aed78bf0124629565ba601a136baebfe51

**Comment by jonrandahl** [comment]
labels are on the staging server for review.

**Comment by nickburne** [comment]
Review and good enough for go live so I will close and add bugs separately! :)
