### ISSUE TITLE
Spell Filters right on the filter button

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#55]

**Comment by jonrandahl** [comment]
This is updated, I'll be pushing to staging when the others are done too.

![image](https://user-images.githubusercontent.com/39102/51121135-929ecc00-180e-11e9-808e-cc9bfd7ff643.png)


![image](https://user-images.githubusercontent.com/39102/51121153-9d596100-180e-11e9-8669-27b082683bb6.png)
