### ISSUE TITLE
Put HelpScout Becon script in app for live chat support

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#63]

**Comment by nickburne** [comment]
<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script>
<script type="text/javascript">window.Beacon('init', '7d0ad71d-abba-43d9-957f-62750c13ab18')</script>

**Comment by nickburne** [comment]
<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script>
<script type="text/javascript">window.Beacon('init', '3509ba1a-90d3-4915-8edb-86241551da9a')</script>

**Comment by nickburne** [comment]
--------- Forwarded message ---------
From: Disha Mungra <help@helpscout.com>
Date: Thu, 14 Feb 2019 at 02:04
Subject: Re: Issues with beacon
To: Harry Gardner <harry@givepanel.com>


Hi Harry, 

I've had a look at the staging site (https://staging.givepanel.com) and I was able to see the Beacon loading in that instance, which is great! Here's a screenshot of my view: http://c.hlp.sc/9dc3a3ade5a6 - could you please let me know if that's showing up on your end now?

Regarding the app.givepanel.com, I'm being prompted to login at https://app.givepanel.com/login. Could you let me know if the Beacon is supposed to be embedded on the login page itself, or I need login credentials to see the page you're having trouble with? I wasn't able to find the embed codes on the login page, I'm afraid.

I'll keep an eye out for your reply, thanks :)

Disha Mungra 
help@helpscout.com   
New to Help Scout? Check out our live demo schedule.

**Comment by jonrandahl** [comment]
![image](https://user-images.githubusercontent.com/39102/53238651-ba951100-3691-11e9-9a65-0fcfcafdeb7d.png)

Updated on all instances
