### ISSUE TITLE
Account Settings Delete wording

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#79]
In the Account Settings we should create a new tab (which should be the first tab) called "General"

Under General there should be headings (h2?) for each area. 

There should be a h2 called "Delete your account". 

Under this heading there should be wording as follows:

"To delete your GivePanel account please email help@givepanel.com and we can do it for you".

**Comment by jonrandahl** [comment]
Updated

![image](https://user-images.githubusercontent.com/39102/53023015-56393e00-3454-11e9-860b-29eae3c148f0.png)

**Comment by jonrandahl** [comment]
deployed to https://staging.givepanel.com for testing
