### ISSUE TITLE
Data structure for better performance and scalability

### ISSUE THREAD

**Issue by shramee** [NickBurneConsulting-GivePanel/givepanel#86]
Too many transactions to parse impeding performance and scalability

To resolve we can have new data structure like this...

`charities`/`${uid}`/`transactions`/`yyyy-mm`/ `${transactionID}`

and

`charities`/`${uid}`/`transactions-all`/ `${transactionID}`

so we have transactions at 2 places 🙂 

@jonrandahl and @nickburne to review 😉

**Comment by nickburne** [comment]
Ok, so @jonrandahl and I spoke about this and we think it's best to divide it.

Jon can do:
``chairities`/`${uid}`/`transactions-all`/ `${transactionID}``

Shramee can do:
``chairities`/`${uid}`/`transactions`/`yyyy-mm`/ `${transactionID}`` with his work on the uploader

**Comment by shramee** [comment]
Aye cool 😄 
Working on `A` first then 😉

**Comment by nickburne** [comment]
@shramee please do A and B (so please do ALL this ticket) based on the latest conversation we had on Slack.

**Comment by nickburne** [comment]
@shramee - please confirm this has been resolved with both the transactions-all and the monthly breakdowns

**Comment by nickburne** [comment]
@shramee - it is taking us a lot of time to understand your tickets and what you have ACTUALLY done. I don't want @jon-humphrey spending time trying to figure out what you have done from your code, when a simple comment on a ticket is much quicker.

Please update this ticket with what you have ACTUALLY done as we have tested on staging and there are still performance issues.

**Comment by jonrandahl** [comment]
@shramee here's a video showing you what we're seeing on the dashboard with your latest updates included.

https://www.useloom.com/share/071d5273f8da4f3f9e173c249b6da8f2

Let me know if you have any questions!

**Comment by jonrandahl** [comment]
Here's the link from today:
https://www.useloom.com/share/d8177cef9f264d4c87245f44f100b50a

**Comment by shramee** [comment]
This is ready to have a look...

**Comment by shramee** [comment]
Let's do a separate ticket for date controls on fundraisers, shall we..?

**Comment by jonrandahl** [comment]
@shramee I'm not closing this as we're still seeing the delay on fundraisers loading, I'm not 100% sure what you've done to resolve this so I'd appreciate some more information here in a comment. 

I'm reassigning this to you for now.

**Comment by shramee** [comment]
Fundraisers load time issue continued in #227

**Comment by shramee** [comment]
This is done I think...
Let me know if I am forgetting sth @jonrandahl @nickburne 😉
