### ISSUE TITLE
CSV Uploader

### ISSUE THREAD

**Issue by jonrandahl** [NickBurneConsulting-GivePanel/givepanel#87]
**Feature Request**
The CSV Transaction Report uploader functionality works with the two cloud functions: `csv2json` and `json2data`. 

I chose this two function approach as when I attempted to process all the transactions in a single cloud function, when the uploaded transaction report contained more than 1400 rows the system errored with an `Out of Memory` exception, even when I assigned the maximum 2GB allowance for the method, alongside a 9 minute timeout period.

Separating each requirement into individual cloud functions allows us to allocate the maximums to each function thereby doubling our memory and timeout allowance!

#### CSV2JSON
`csv2json` digests the uploaded csv file, parses each transaction via PapaParse and writes the transformed data onto a new JSON file for the second cloud function to digest. 

This function is working and has successfully transformed the most significant data set we currently have, 23000 rows, as expected.

#### JSON2DATA
`json2data` is based on [Use Node to parse data to Firestore](https://blog.cong-li.com/use-node-to-parse-data-to-firestore/), which reads the newly formatted JSON file via the node package `Readline` to read each line, append it to a temporary array, pause the main loop in order to then loop through the temp array via batch writes to add the processed lines to the database, and then resumes the main loop while clearing the temporary array and releasing the memory used to prevent the function from falling over. 

**Issues**

The issue in the `json2data` function is that `Readline` looks for a carriage return character, `\n`, to delimit each line, and the JSON returned from the first function is proper JSON, delimited by commas, `.`. 

Sadly there's no way to change that in the `Readline` module options.

**What I think will work**
Create a function that will loop over the JSON objects and pass them into the Database without timing out; this would prevent the function from falling over due to the firestore write limit for single batch => size:10MB, doc amount: 500, rate: 1/s

**Current Code**
You can find the current version on the [Uploader.v3](https://github.com/NickBurneConsulting-GivePanel/givepanel/blob/uploader.v3/client/functions/index.js) branch. 

I'm happy to answer any questions you might have!

Jon

**Comment by shramee** [comment]
Let's have it cover `A` in #86

**Comment by nickburne** [comment]
@nickburne to test on Staging

**Comment by nickburne** [comment]
Nick tested on Staging with the large Sands file and it didn't work. Will speak with @jonrandahl about it.

**Comment by jonrandahl** [comment]
@shramee I've just tested the Sands data on staging after updating the cloud functions with your latest version and the uploader is falling over on the number of transactions with the following error:

`Error: 10 ABORTED: Too much contention on these documents. Please try again.`

I've done a search on this and found this information from Jen Persons, a Firebase evangelist, and here's the link for you:

https://stackoverflow.com/a/52340150/5760177

I've checked the code in the repo, which I deployed to my dev, staging, and the demo instances is the same as what's on your cloud functions on the Dev2 instance so please let me know if you need any help with this! 

👍

**Comment by shramee** [comment]
Fixed for admin by @jonrandahl 😄
