### ISSUE TITLE
Endpoints to generate and cache stats

### ISSUE THREAD

**Issue by shramee** [NickBurneConsulting-GivePanel/givepanel#94]
Let's have an endpoint to generate and cache these stats...

1. All time
2. Annual
3. Monthly

Idea is to avoid bringing in all transactions on client side every time...

@jonrandahl @nickburne to follow

**Comment by nickburne** [comment]
@shramee - question - is this going to solve the loading delays for the large data set?

**Comment by shramee** [comment]
Aye 😁

**Comment by shramee** [comment]
@nickburne @jonrandahl Not sure we need this anymore...
